trigger:
- main

pool:
  name: 'notagent'  # Use your self-hosted agent pool name

steps:
# Step to checkout code from GitHub
- checkout: self  # This ensures the code is pulled from the repository

# Step to run the PowerShell script
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/scripts/my_script.ps1'