trigger:
- main

pool:
  name: 'MySelfHostedPool'  # Your self-hosted agent pool name

steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: './scripts/my_script.ps1'  # Path to your PowerShell script